import * as echarts from 'echarts';

import 中国 from '@/mock/areas/china.json';
echarts.registerMap('中国', 中国);
import 贵州省 from '@/mock/areas/520000.json';
echarts.registerMap('贵州省', 贵州省);
import 安顺市 from '@/mock/areas/520400.json';
echarts.registerMap('安顺市', 安顺市);
import 毕节市 from '@/mock/areas/520500.json';
echarts.registerMap('毕节市', 毕节市);
import 贵阳市 from '@/mock/areas/520100.json';
echarts.registerMap('贵阳市', 贵阳市);
import 六盘水市 from '@/mock/areas/520200.json';
echarts.registerMap('六盘水市', 六盘水市);
import 黔西南布依族苗族自治州 from '@/mock/areas/522300.json';
echarts.registerMap('黔西南布依族苗族自治州', 黔西南布依族苗族自治州);
import 黔南布依族苗族自治州 from '@/mock/areas/522700.json';
echarts.registerMap('黔南布依族苗族自治州', 黔南布依族苗族自治州);
import 黔东南苗族侗族自治州 from '@/mock/areas/522600.json';
echarts.registerMap('黔东南苗族侗族自治州', 黔东南苗族侗族自治州);
import 铜仁市 from '@/mock/areas/520600.json';
echarts.registerMap('铜仁市', 铜仁市);
import 遵义市 from '@/mock/areas/520300.json';
echarts.registerMap('遵义市', 遵义市);
import 澳门特别行政区 from '@/mock/areas/820000.json';
echarts.registerMap('澳门特别行政区', 澳门特别行政区);
import 福建省 from '@/mock/areas/350000.json';
echarts.registerMap('福建省', 福建省);
import 福州市 from '@/mock/areas/350100.json';
echarts.registerMap('福州市', 福州市);
import 龙岩市 from '@/mock/areas/350800.json';
echarts.registerMap('龙岩市', 龙岩市);
import 南平市 from '@/mock/areas/350700.json';
echarts.registerMap('南平市', 南平市);
import 宁德市 from '@/mock/areas/350900.json';
echarts.registerMap('宁德市', 宁德市);
import 厦门市 from '@/mock/areas/350200.json';
echarts.registerMap('厦门市', 厦门市);
import 莆田市 from '@/mock/areas/350300.json';
echarts.registerMap('莆田市', 莆田市);
import 三明市 from '@/mock/areas/350400.json';
echarts.registerMap('三明市', 三明市);
import 泉州市 from '@/mock/areas/350500.json';
echarts.registerMap('泉州市', 泉州市);
import 漳州市 from '@/mock/areas/350600.json';
echarts.registerMap('漳州市', 漳州市);
import 重庆市 from '@/mock/areas/500000.json';
echarts.registerMap('重庆市', 重庆市);
import 重庆城区 from '@/mock/areas/500100.json';
echarts.registerMap('重庆城区', 重庆城区);
import 重庆郊县 from '@/mock/areas/500200.json';
echarts.registerMap('重庆郊县', 重庆郊县);
import 海南省 from '@/mock/areas/460000.json';
echarts.registerMap('海南省', 海南省);
import 儋州市 from '@/mock/areas/460400.json';
echarts.registerMap('儋州市', 儋州市);
import 海口市 from '@/mock/areas/460100.json';
echarts.registerMap('海口市', 海口市);
import 三沙市 from '@/mock/areas/460300.json';
echarts.registerMap('三沙市', 三沙市);
import 三亚市 from '@/mock/areas/460200.json';
echarts.registerMap('三亚市', 三亚市);
import 广东省 from '@/mock/areas/440000.json';
echarts.registerMap('广东省', 广东省);
import 中山市 from '@/mock/areas/442000.json';
echarts.registerMap('中山市', 中山市);
import 东沙群岛 from '@/mock/areas/442100.json';
echarts.registerMap('东沙群岛', 东沙群岛);
import 潮州市 from '@/mock/areas/445100.json';
echarts.registerMap('潮州市', 潮州市);
import 东莞市 from '@/mock/areas/441900.json';
echarts.registerMap('东莞市', 东莞市);
import 佛山市 from '@/mock/areas/440600.json';
echarts.registerMap('佛山市', 佛山市);
import 广州市 from '@/mock/areas/440100.json';
echarts.registerMap('广州市', 广州市);
import 河源市 from '@/mock/areas/441600.json';
echarts.registerMap('河源市', 河源市);
import 惠州市 from '@/mock/areas/441300.json';
echarts.registerMap('惠州市', 惠州市);
import 江门市 from '@/mock/areas/440700.json';
echarts.registerMap('江门市', 江门市);
import 揭阳市 from '@/mock/areas/445200.json';
echarts.registerMap('揭阳市', 揭阳市);
import 茂名市 from '@/mock/areas/440900.json';
echarts.registerMap('茂名市', 茂名市);
import 梅州市 from '@/mock/areas/441400.json';
echarts.registerMap('梅州市', 梅州市);
import 清远市 from '@/mock/areas/441800.json';
echarts.registerMap('清远市', 清远市);
import 汕头市 from '@/mock/areas/440500.json';
echarts.registerMap('汕头市', 汕头市);
import 汕尾市 from '@/mock/areas/441500.json';
echarts.registerMap('汕尾市', 汕尾市);
import 韶关市 from '@/mock/areas/440200.json';
echarts.registerMap('韶关市', 韶关市);
import 深圳市 from '@/mock/areas/440300.json';
echarts.registerMap('深圳市', 深圳市);
import 阳江市 from '@/mock/areas/441700.json';
echarts.registerMap('阳江市', 阳江市);
import 云浮市 from '@/mock/areas/445300.json';
echarts.registerMap('云浮市', 云浮市);
import 湛江市 from '@/mock/areas/440800.json';
echarts.registerMap('湛江市', 湛江市);
import 肇庆市 from '@/mock/areas/441200.json';
echarts.registerMap('肇庆市', 肇庆市);
import 珠海市 from '@/mock/areas/440400.json';
echarts.registerMap('珠海市', 珠海市);
import 广西省 from '@/mock/areas/450000.json';
echarts.registerMap('广西省', 广西省);
import 北海市 from '@/mock/areas/450500.json';
echarts.registerMap('北海市', 北海市);
import 百色市 from '@/mock/areas/451000.json';
echarts.registerMap('百色市', 百色市);
import 崇左市 from '@/mock/areas/451400.json';
echarts.registerMap('崇左市', 崇左市);
import 防城港市 from '@/mock/areas/450600.json';
echarts.registerMap('防城港市', 防城港市);
import 桂林市 from '@/mock/areas/450300.json';
echarts.registerMap('桂林市', 桂林市);
import 贵港市 from '@/mock/areas/450800.json';
echarts.registerMap('贵港市', 贵港市);
import 河池市 from '@/mock/areas/451200.json';
echarts.registerMap('河池市', 河池市);
import 贺州市 from '@/mock/areas/451100.json';
echarts.registerMap('贺州市', 贺州市);
import 来宾市 from '@/mock/areas/451300.json';
echarts.registerMap('来宾市', 来宾市);
import 柳州市 from '@/mock/areas/450200.json';
echarts.registerMap('柳州市', 柳州市);
import 南宁市 from '@/mock/areas/450100.json';
echarts.registerMap('南宁市', 南宁市);
import 钦州市 from '@/mock/areas/450700.json';
echarts.registerMap('钦州市', 钦州市);
import 梧州市 from '@/mock/areas/450400.json';
echarts.registerMap('梧州市', 梧州市);
import 玉林市 from '@/mock/areas/450900.json';
echarts.registerMap('玉林市', 玉林市);
import 山西省 from '@/mock/areas/140000.json';
echarts.registerMap('山西省', 山西省);
import 大同市 from '@/mock/areas/140200.json';
echarts.registerMap('大同市', 大同市);
import 晋城市 from '@/mock/areas/140500.json';
echarts.registerMap('晋城市', 晋城市);
import 晋中市 from '@/mock/areas/140700.json';
echarts.registerMap('晋中市', 晋中市);
import 临汾市 from '@/mock/areas/141000.json';
echarts.registerMap('临汾市', 临汾市);
import 吕梁市 from '@/mock/areas/141100.json';
echarts.registerMap('吕梁市', 吕梁市);
import 朔州市 from '@/mock/areas/140600.json';
echarts.registerMap('朔州市', 朔州市);
import 太原市 from '@/mock/areas/140100.json';
echarts.registerMap('太原市', 太原市);
import 阳泉市 from '@/mock/areas/140300.json';
echarts.registerMap('阳泉市', 阳泉市);
import 忻州市 from '@/mock/areas/140900.json';
echarts.registerMap('忻州市', 忻州市);
import 运城市 from '@/mock/areas/140800.json';
echarts.registerMap('运城市', 运城市);
import 长治市 from '@/mock/areas/140400.json';
echarts.registerMap('长治市', 长治市);
import 甘肃省 from '@/mock/areas/620000.json';
echarts.registerMap('甘肃省', 甘肃省);
import 白银市 from '@/mock/areas/620400.json';
echarts.registerMap('白银市', 白银市);
import 甘南藏族自治州 from '@/mock/areas/623000.json';
echarts.registerMap('甘南藏族自治州', 甘南藏族自治州);
import 定西市 from '@/mock/areas/621100.json';
echarts.registerMap('定西市', 定西市);
import 嘉峪关市 from '@/mock/areas/620200.json';
echarts.registerMap('嘉峪关市', 嘉峪关市);
import 金昌市 from '@/mock/areas/620300.json';
echarts.registerMap('金昌市', 金昌市);
import 酒泉市 from '@/mock/areas/620900.json';
echarts.registerMap('酒泉市', 酒泉市);
import 兰州市 from '@/mock/areas/620100.json';
echarts.registerMap('兰州市', 兰州市);
import 临夏回族自治州 from '@/mock/areas/622900.json';
echarts.registerMap('临夏回族自治州', 临夏回族自治州);
import 陇南市 from '@/mock/areas/621200.json';
echarts.registerMap('陇南市', 陇南市);
import 平凉市 from '@/mock/areas/620800.json';
echarts.registerMap('平凉市', 平凉市);
import 庆阳市 from '@/mock/areas/621000.json';
echarts.registerMap('庆阳市', 庆阳市);
import 天水市 from '@/mock/areas/620500.json';
echarts.registerMap('天水市', 天水市);
import 武威市 from '@/mock/areas/620600.json';
echarts.registerMap('武威市', 武威市);
import 张掖市 from '@/mock/areas/620700.json';
echarts.registerMap('张掖市', 张掖市);
import 台湾省 from '@/mock/areas/710000.json';
echarts.registerMap('台湾省', 台湾省);
import 江苏省 from '@/mock/areas/320000.json';
echarts.registerMap('江苏省', 江苏省);
import 常州市 from '@/mock/areas/320400.json';
echarts.registerMap('常州市', 常州市);
import 淮安市 from '@/mock/areas/320800.json';
echarts.registerMap('淮安市', 淮安市);
import 连云港市 from '@/mock/areas/320700.json';
echarts.registerMap('连云港市', 连云港市);
import 南京市 from '@/mock/areas/320100.json';
echarts.registerMap('南京市', 南京市);
import 南通市 from '@/mock/areas/320600.json';
echarts.registerMap('南通市', 南通市);
import 苏州市 from '@/mock/areas/320500.json';
echarts.registerMap('苏州市', 苏州市);
import 宿迁市 from '@/mock/areas/321300.json';
echarts.registerMap('宿迁市', 宿迁市);
import 泰州市 from '@/mock/areas/321200.json';
echarts.registerMap('泰州市', 泰州市);
import 无锡市 from '@/mock/areas/320200.json';
echarts.registerMap('无锡市', 无锡市);
import 徐州市 from '@/mock/areas/320300.json';
echarts.registerMap('徐州市', 徐州市);
import 盐城市 from '@/mock/areas/320900.json';
echarts.registerMap('盐城市', 盐城市);
import 扬州市 from '@/mock/areas/321000.json';
echarts.registerMap('扬州市', 扬州市);
import 镇江市 from '@/mock/areas/321100.json';
echarts.registerMap('镇江市', 镇江市);
import 河南省 from '@/mock/areas/410000.json';
echarts.registerMap('河南省', 河南省);
import 安阳市 from '@/mock/areas/410500.json';
echarts.registerMap('安阳市', 安阳市);
import 鹤壁市 from '@/mock/areas/410600.json';
echarts.registerMap('鹤壁市', 鹤壁市);
import 焦作市 from '@/mock/areas/410800.json';
echarts.registerMap('焦作市', 焦作市);
import 开封市 from '@/mock/areas/410200.json';
echarts.registerMap('开封市', 开封市);
import 漯河市 from '@/mock/areas/411100.json';
echarts.registerMap('漯河市', 漯河市);
import 洛阳市 from '@/mock/areas/410300.json';
echarts.registerMap('洛阳市', 洛阳市);
import 南阳市 from '@/mock/areas/411300.json';
echarts.registerMap('南阳市', 南阳市);
import 平顶山市 from '@/mock/areas/410400.json';
echarts.registerMap('平顶山市', 平顶山市);
import 濮阳市 from '@/mock/areas/410900.json';
echarts.registerMap('濮阳市', 濮阳市);
import 商丘市 from '@/mock/areas/411400.json';
echarts.registerMap('商丘市', 商丘市);
import 三门峡市 from '@/mock/areas/411200.json';
echarts.registerMap('三门峡市', 三门峡市);
import 许昌市 from '@/mock/areas/411000.json';
echarts.registerMap('许昌市', 许昌市);
import 新乡市 from '@/mock/areas/410700.json';
echarts.registerMap('新乡市', 新乡市);
import 信阳市 from '@/mock/areas/411500.json';
echarts.registerMap('信阳市', 信阳市);
import 郑州市 from '@/mock/areas/410100.json';
echarts.registerMap('郑州市', 郑州市);
import 周口市 from '@/mock/areas/411600.json';
echarts.registerMap('周口市', 周口市);
import 驻马店市 from '@/mock/areas/411700.json';
echarts.registerMap('驻马店市', 驻马店市);
import 河北省 from '@/mock/areas/130000.json';
echarts.registerMap('河北省', 河北省);
import 保定市 from '@/mock/areas/130600.json';
echarts.registerMap('保定市', 保定市);
import 沧州市 from '@/mock/areas/130900.json';
echarts.registerMap('沧州市', 沧州市);
import 承德市 from '@/mock/areas/130800.json';
echarts.registerMap('承德市', 承德市);
import 邯郸市 from '@/mock/areas/130400.json';
echarts.registerMap('邯郸市', 邯郸市);
import 衡水市 from '@/mock/areas/131100.json';
echarts.registerMap('衡水市', 衡水市);
import 廊坊市 from '@/mock/areas/131000.json';
echarts.registerMap('廊坊市', 廊坊市);
import 秦皇岛市 from '@/mock/areas/130300.json';
echarts.registerMap('秦皇岛市', 秦皇岛市);
import 石家庄市 from '@/mock/areas/130100.json';
echarts.registerMap('石家庄市', 石家庄市);
import 唐山市 from '@/mock/areas/130200.json';
echarts.registerMap('唐山市', 唐山市);
import 邢台市 from '@/mock/areas/130500.json';
echarts.registerMap('邢台市', 邢台市);
import 张家口市 from '@/mock/areas/130700.json';
echarts.registerMap('张家口市', 张家口市);
import 安徽省 from '@/mock/areas/340000.json';
echarts.registerMap('安徽省', 安徽省);
import 安庆市 from '@/mock/areas/340800.json';
echarts.registerMap('安庆市', 安庆市);
import 蚌埠市 from '@/mock/areas/340300.json';
echarts.registerMap('蚌埠市', 蚌埠市);
import 亳州市 from '@/mock/areas/341600.json';
echarts.registerMap('亳州市', 亳州市);
import 滁州市 from '@/mock/areas/341100.json';
echarts.registerMap('滁州市', 滁州市);
import 池州市 from '@/mock/areas/341700.json';
echarts.registerMap('池州市', 池州市);
import 阜阳市 from '@/mock/areas/341200.json';
echarts.registerMap('阜阳市', 阜阳市);
import 合肥市 from '@/mock/areas/340100.json';
echarts.registerMap('合肥市', 合肥市);
import 黄山市 from '@/mock/areas/341000.json';
echarts.registerMap('黄山市', 黄山市);
import 淮南市 from '@/mock/areas/340400.json';
echarts.registerMap('淮南市', 淮南市);
import 淮北市 from '@/mock/areas/340600.json';
echarts.registerMap('淮北市', 淮北市);
import 六安市 from '@/mock/areas/341500.json';
echarts.registerMap('六安市', 六安市);
import 马鞍山市 from '@/mock/areas/340500.json';
echarts.registerMap('马鞍山市', 马鞍山市);
import 铜陵市 from '@/mock/areas/340700.json';
echarts.registerMap('铜陵市', 铜陵市);
import 宿州市 from '@/mock/areas/341300.json';
echarts.registerMap('宿州市', 宿州市);
import 芜湖市 from '@/mock/areas/340200.json';
echarts.registerMap('芜湖市', 芜湖市);
import 宣城市 from '@/mock/areas/341800.json';
echarts.registerMap('宣城市', 宣城市);
import 湖南省 from '@/mock/areas/430000.json';
echarts.registerMap('湖南省', 湖南省);
import 常德市 from '@/mock/areas/430700.json';
echarts.registerMap('常德市', 常德市);
import 郴州市 from '@/mock/areas/431000.json';
echarts.registerMap('郴州市', 郴州市);
import 衡阳市 from '@/mock/areas/430400.json';
echarts.registerMap('衡阳市', 衡阳市);
import 娄底市 from '@/mock/areas/431300.json';
echarts.registerMap('娄底市', 娄底市);
import 邵阳市 from '@/mock/areas/430500.json';
echarts.registerMap('邵阳市', 邵阳市);
import 湘西土家族苗族自治州 from '@/mock/areas/433100.json';
echarts.registerMap('湘西土家族苗族自治州', 湘西土家族苗族自治州);
import 湘潭市 from '@/mock/areas/430300.json';
echarts.registerMap('湘潭市', 湘潭市);
import 永州市 from '@/mock/areas/431100.json';
echarts.registerMap('永州市', 永州市);
import 益阳市 from '@/mock/areas/430900.json';
echarts.registerMap('益阳市', 益阳市);
import 张家界市 from '@/mock/areas/430800.json';
echarts.registerMap('张家界市', 张家界市);
import 株洲市 from '@/mock/areas/430200.json';
echarts.registerMap('株洲市', 株洲市);
import 岳阳市 from '@/mock/areas/430600.json';
echarts.registerMap('岳阳市', 岳阳市);
import 长沙市 from '@/mock/areas/430100.json';
echarts.registerMap('长沙市', 长沙市);
import 怀化市 from '@/mock/areas/431200.json';
echarts.registerMap('怀化市', 怀化市);
import 上海市 from '@/mock/areas/310000.json';
echarts.registerMap('上海市', 上海市);
import 上海城区 from '@/mock/areas/310100.json';
echarts.registerMap('上海城区', 上海城区);
import 湖北省 from '@/mock/areas/420000.json';
echarts.registerMap('湖北省', 湖北省);
import 鄂州市 from '@/mock/areas/420700.json';
echarts.registerMap('鄂州市', 鄂州市);
import 恩施土家族苗族自治州 from '@/mock/areas/422800.json';
echarts.registerMap('恩施土家族苗族自治州', 恩施土家族苗族自治州);
import 黄石市 from '@/mock/areas/420200.json';
echarts.registerMap('黄石市', 黄石市);
import 黄冈市 from '@/mock/areas/421100.json';
echarts.registerMap('黄冈市', 黄冈市);
import 荆门市 from '@/mock/areas/420800.json';
echarts.registerMap('荆门市', 荆门市);
import 荆州市 from '@/mock/areas/421000.json';
echarts.registerMap('荆州市', 荆州市);
import 随州市 from '@/mock/areas/421300.json';
echarts.registerMap('随州市', 随州市);
import 十堰市 from '@/mock/areas/420300.json';
echarts.registerMap('十堰市', 十堰市);
import 武汉市 from '@/mock/areas/420100.json';
echarts.registerMap('武汉市', 武汉市);
import 孝感市 from '@/mock/areas/420900.json';
echarts.registerMap('孝感市', 孝感市);
import 襄阳市 from '@/mock/areas/420600.json';
echarts.registerMap('襄阳市', 襄阳市);
import 咸宁市 from '@/mock/areas/421200.json';
echarts.registerMap('咸宁市', 咸宁市);
import 宜昌市 from '@/mock/areas/420500.json';
echarts.registerMap('宜昌市', 宜昌市);
import 黑龙江省 from '@/mock/areas/230000.json';
echarts.registerMap('黑龙江省', 黑龙江省);
import 大庆市 from '@/mock/areas/230600.json';
echarts.registerMap('大庆市', 大庆市);
import 大兴安岭地区 from '@/mock/areas/232700.json';
echarts.registerMap('大兴安岭地区', 大兴安岭地区);
import 哈尔滨市 from '@/mock/areas/230100.json';
echarts.registerMap('哈尔滨市', 哈尔滨市);
import 鹤岗市 from '@/mock/areas/230400.json';
echarts.registerMap('鹤岗市', 鹤岗市);
import 黑河市 from '@/mock/areas/231100.json';
echarts.registerMap('黑河市', 黑河市);
import 鸡西市 from '@/mock/areas/230300.json';
echarts.registerMap('鸡西市', 鸡西市);
import 佳木斯市 from '@/mock/areas/230800.json';
echarts.registerMap('佳木斯市', 佳木斯市);
import 牡丹江市 from '@/mock/areas/231000.json';
echarts.registerMap('牡丹江市', 牡丹江市);
import 齐齐哈尔市 from '@/mock/areas/230200.json';
echarts.registerMap('齐齐哈尔市', 齐齐哈尔市);
import 七台河市 from '@/mock/areas/230900.json';
echarts.registerMap('七台河市', 七台河市);
import 绥化市 from '@/mock/areas/231200.json';
echarts.registerMap('绥化市', 绥化市);
import 双鸭山市 from '@/mock/areas/230500.json';
echarts.registerMap('双鸭山市', 双鸭山市);
import 伊春市 from '@/mock/areas/230700.json';
echarts.registerMap('伊春市', 伊春市);
import 青海省 from '@/mock/areas/630000.json';
echarts.registerMap('青海省', 青海省);
import 果洛藏族自治州 from '@/mock/areas/632600.json';
echarts.registerMap('果洛藏族自治州', 果洛藏族自治州);
import 海东市 from '@/mock/areas/630200.json';
echarts.registerMap('海东市', 海东市);
import 海北藏族自治州 from '@/mock/areas/632200.json';
echarts.registerMap('海北藏族自治州', 海北藏族自治州);
import 海西蒙古族藏族自治州 from '@/mock/areas/632800.json';
echarts.registerMap('海西蒙古族藏族自治州', 海西蒙古族藏族自治州);
import 海南藏族自治州 from '@/mock/areas/632500.json';
echarts.registerMap('海南藏族自治州', 海南藏族自治州);
import 黄南藏族自治州 from '@/mock/areas/632300.json';
echarts.registerMap('黄南藏族自治州', 黄南藏族自治州);
import 西宁市 from '@/mock/areas/630100.json';
echarts.registerMap('西宁市', 西宁市);
import 玉树藏族自治州 from '@/mock/areas/632700.json';
echarts.registerMap('玉树藏族自治州', 玉树藏族自治州);
import 江西省 from '@/mock/areas/360000.json';
echarts.registerMap('江西省', 江西省);
import 抚州市 from '@/mock/areas/361000.json';
echarts.registerMap('抚州市', 抚州市);
import 赣州市 from '@/mock/areas/360700.json';
echarts.registerMap('赣州市', 赣州市);
import 吉安市 from '@/mock/areas/360800.json';
echarts.registerMap('吉安市', 吉安市);
import 九江市 from '@/mock/areas/360400.json';
echarts.registerMap('九江市', 九江市);
import 景德镇市 from '@/mock/areas/360200.json';
echarts.registerMap('景德镇市', 景德镇市);
import 南昌市 from '@/mock/areas/360100.json';
echarts.registerMap('南昌市', 南昌市);
import 萍乡市 from '@/mock/areas/360300.json';
echarts.registerMap('萍乡市', 萍乡市);
import 上饶市 from '@/mock/areas/361100.json';
echarts.registerMap('上饶市', 上饶市);
import 新余市 from '@/mock/areas/360500.json';
echarts.registerMap('新余市', 新余市);
import 宜春市 from '@/mock/areas/360900.json';
echarts.registerMap('宜春市', 宜春市);
import 鹰潭市 from '@/mock/areas/360600.json';
echarts.registerMap('鹰潭市', 鹰潭市);
import 内蒙古自治区 from '@/mock/areas/150000.json';
echarts.registerMap('内蒙古自治区', 内蒙古自治区);
import 阿拉善盟 from '@/mock/areas/152900.json';
echarts.registerMap('阿拉善盟', 阿拉善盟);
import 巴彦淖尔市 from '@/mock/areas/150800.json';
echarts.registerMap('巴彦淖尔市', 巴彦淖尔市);
import 包头市 from '@/mock/areas/150200.json';
echarts.registerMap('包头市', 包头市);
import 赤峰市 from '@/mock/areas/150400.json';
echarts.registerMap('赤峰市', 赤峰市);
import 鄂尔多斯市 from '@/mock/areas/150600.json';
echarts.registerMap('鄂尔多斯市', 鄂尔多斯市);
import 呼和浩特市 from '@/mock/areas/150100.json';
echarts.registerMap('呼和浩特市', 呼和浩特市);
import 呼伦贝尔市 from '@/mock/areas/150700.json';
echarts.registerMap('呼伦贝尔市', 呼伦贝尔市);
import 乌海市 from '@/mock/areas/150300.json';
echarts.registerMap('乌海市', 乌海市);
import 乌兰察布市 from '@/mock/areas/150900.json';
echarts.registerMap('乌兰察布市', 乌兰察布市);
import 通辽市 from '@/mock/areas/150500.json';
echarts.registerMap('通辽市', 通辽市);
import 锡林郭勒盟 from '@/mock/areas/152500.json';
echarts.registerMap('锡林郭勒盟', 锡林郭勒盟);
import 兴安盟 from '@/mock/areas/152200.json';
echarts.registerMap('兴安盟', 兴安盟);
import 辽宁省 from '@/mock/areas/210000.json';
echarts.registerMap('辽宁省', 辽宁省);
import 鞍山市 from '@/mock/areas/210300.json';
echarts.registerMap('鞍山市', 鞍山市);
import 本溪市 from '@/mock/areas/210500.json';
echarts.registerMap('本溪市', 本溪市);
import 朝阳市 from '@/mock/areas/211300.json';
echarts.registerMap('朝阳市', 朝阳市);
import 丹东市 from '@/mock/areas/210600.json';
echarts.registerMap('丹东市', 丹东市);
import 大连市 from '@/mock/areas/210200.json';
echarts.registerMap('大连市', 大连市);
import 抚顺市 from '@/mock/areas/210400.json';
echarts.registerMap('抚顺市', 抚顺市);
import 阜新市 from '@/mock/areas/210900.json';
echarts.registerMap('阜新市', 阜新市);
import 葫芦岛市 from '@/mock/areas/211400.json';
echarts.registerMap('葫芦岛市', 葫芦岛市);
import 锦州市 from '@/mock/areas/210700.json';
echarts.registerMap('锦州市', 锦州市);
import 辽阳市 from '@/mock/areas/211000.json';
echarts.registerMap('辽阳市', 辽阳市);
import 盘锦市 from '@/mock/areas/211100.json';
echarts.registerMap('盘锦市', 盘锦市);
import 沈阳市 from '@/mock/areas/210100.json';
echarts.registerMap('沈阳市', 沈阳市);
import 铁岭市 from '@/mock/areas/211200.json';
echarts.registerMap('铁岭市', 铁岭市);
import 营口市 from '@/mock/areas/210800.json';
echarts.registerMap('营口市', 营口市);
import 宁夏回族自治区 from '@/mock/areas/640000.json';
echarts.registerMap('宁夏回族自治区', 宁夏回族自治区);
import 固原市 from '@/mock/areas/640400.json';
echarts.registerMap('固原市', 固原市);
import 石嘴山市 from '@/mock/areas/640200.json';
echarts.registerMap('石嘴山市', 石嘴山市);
import 吴忠市 from '@/mock/areas/640300.json';
echarts.registerMap('吴忠市', 吴忠市);
import 银川市 from '@/mock/areas/640100.json';
echarts.registerMap('银川市', 银川市);
import 中卫市 from '@/mock/areas/640500.json';
echarts.registerMap('中卫市', 中卫市);
import 吉林省 from '@/mock/areas/220000.json';
echarts.registerMap('吉林省', 吉林省);
import 白城市 from '@/mock/areas/220800.json';
echarts.registerMap('白城市', 白城市);
import 白山市 from '@/mock/areas/220600.json';
echarts.registerMap('白山市', 白山市);
import 吉林市 from '@/mock/areas/220200.json';
echarts.registerMap('吉林市', 吉林市);
import 辽源市 from '@/mock/areas/220400.json';
echarts.registerMap('辽源市', 辽源市);
import 松原市 from '@/mock/areas/220700.json';
echarts.registerMap('松原市', 松原市);
import 四平市 from '@/mock/areas/220300.json';
echarts.registerMap('四平市', 四平市);
import 通化市 from '@/mock/areas/220500.json';
echarts.registerMap('通化市', 通化市);
import 延边朝鲜族自治州 from '@/mock/areas/222400.json';
echarts.registerMap('延边朝鲜族自治州', 延边朝鲜族自治州);
import 长春市 from '@/mock/areas/220100.json';
echarts.registerMap('长春市', 长春市);
import 山东省 from '@/mock/areas/370000.json';
echarts.registerMap('山东省', 山东省);
import 滨州市 from '@/mock/areas/371600.json';
echarts.registerMap('滨州市', 滨州市);
import 德州市 from '@/mock/areas/371400.json';
echarts.registerMap('德州市', 德州市);
import 东营市 from '@/mock/areas/370500.json';
echarts.registerMap('东营市', 东营市);
import 菏泽市 from '@/mock/areas/371700.json';
echarts.registerMap('菏泽市', 菏泽市);
import 济南市 from '@/mock/areas/370100.json';
echarts.registerMap('济南市', 济南市);
import 济宁市 from '@/mock/areas/370800.json';
echarts.registerMap('济宁市', 济宁市);
import 莱芜市 from '@/mock/areas/371200.json';
echarts.registerMap('莱芜市', 莱芜市);
import 聊城市 from '@/mock/areas/371500.json';
echarts.registerMap('聊城市', 聊城市);
import 临沂市 from '@/mock/areas/371300.json';
echarts.registerMap('临沂市', 临沂市);
import 青岛市 from '@/mock/areas/370200.json';
echarts.registerMap('青岛市', 青岛市);
import 日照市 from '@/mock/areas/371100.json';
echarts.registerMap('日照市', 日照市);
import 泰安市 from '@/mock/areas/370900.json';
echarts.registerMap('泰安市', 泰安市);
import 威海市 from '@/mock/areas/371000.json';
echarts.registerMap('威海市', 威海市);
import 潍坊市 from '@/mock/areas/370700.json';
echarts.registerMap('潍坊市', 潍坊市);
import 烟台市 from '@/mock/areas/370600.json';
echarts.registerMap('烟台市', 烟台市);
import 枣庄市 from '@/mock/areas/370400.json';
echarts.registerMap('枣庄市', 枣庄市);
import 淄博市 from '@/mock/areas/370300.json';
echarts.registerMap('淄博市', 淄博市);
import 陕西省 from '@/mock/areas/610000.json';
echarts.registerMap('陕西省', 陕西省);
import 安康市 from '@/mock/areas/610900.json';
echarts.registerMap('安康市', 安康市);
import 宝鸡市 from '@/mock/areas/610300.json';
echarts.registerMap('宝鸡市', 宝鸡市);
import 汉中市 from '@/mock/areas/610700.json';
echarts.registerMap('汉中市', 汉中市);
import 商洛市 from '@/mock/areas/611000.json';
echarts.registerMap('商洛市', 商洛市);
import 铜川市 from '@/mock/areas/610200.json';
echarts.registerMap('铜川市', 铜川市);
import 渭南市 from '@/mock/areas/610500.json';
echarts.registerMap('渭南市', 渭南市);
import 西安市 from '@/mock/areas/610100.json';
echarts.registerMap('西安市', 西安市);
import 咸阳市 from '@/mock/areas/610400.json';
echarts.registerMap('咸阳市', 咸阳市);
import 延安市 from '@/mock/areas/610600.json';
echarts.registerMap('延安市', 延安市);
import 榆林市 from '@/mock/areas/610800.json';
echarts.registerMap('榆林市', 榆林市);
import 新疆维吾尔自治区 from '@/mock/areas/650000.json';
echarts.registerMap('新疆维吾尔自治区', 新疆维吾尔自治区);
import 阿克苏地区 from '@/mock/areas/652900.json';
echarts.registerMap('阿克苏地区', 阿克苏地区);
import 阿勒泰地区 from '@/mock/areas/654300.json';
echarts.registerMap('阿勒泰地区', 阿勒泰地区);
import 昌吉回族自治州 from '@/mock/areas/652300.json';
echarts.registerMap('昌吉回族自治州', 昌吉回族自治州);
import 巴音郭楞蒙古自治州 from '@/mock/areas/652800.json';
echarts.registerMap('巴音郭楞蒙古自治州', 巴音郭楞蒙古自治州);
import 博尔塔拉蒙古自治州 from '@/mock/areas/652700.json';
echarts.registerMap('博尔塔拉蒙古自治州', 博尔塔拉蒙古自治州);
import 哈密市 from '@/mock/areas/650500.json';
echarts.registerMap('哈密市', 哈密市);
import 和田地区 from '@/mock/areas/653200.json';
echarts.registerMap('和田地区', 和田地区);
import 克孜勒苏柯尔克孜自治州 from '@/mock/areas/653000.json';
echarts.registerMap('克孜勒苏柯尔克孜自治州', 克孜勒苏柯尔克孜自治州);
import 克拉玛依市 from '@/mock/areas/650200.json';
echarts.registerMap('克拉玛依市', 克拉玛依市);
import 喀什地区 from '@/mock/areas/653100.json';
echarts.registerMap('喀什地区', 喀什地区);
import 塔城地区 from '@/mock/areas/654200.json';
echarts.registerMap('塔城地区', 塔城地区);
import 乌鲁木齐市 from '@/mock/areas/650100.json';
echarts.registerMap('乌鲁木齐市', 乌鲁木齐市);
import 吐鲁番市 from '@/mock/areas/650400.json';
echarts.registerMap('吐鲁番市', 吐鲁番市);
import 伊犁哈萨克自治州 from '@/mock/areas/654000.json';
echarts.registerMap('伊犁哈萨克自治州', 伊犁哈萨克自治州);
import 天津市 from '@/mock/areas/120000.json';
echarts.registerMap('天津市', 天津市);
import 四川省 from '@/mock/areas/510000.json';
echarts.registerMap('四川省', 四川省);
import 阿坝藏族羌族自治州 from '@/mock/areas/513200.json';
echarts.registerMap('阿坝藏族羌族自治州', 阿坝藏族羌族自治州);
import 巴中市 from '@/mock/areas/511900.json';
echarts.registerMap('巴中市', 巴中市);
import 成都市 from '@/mock/areas/510100.json';
echarts.registerMap('成都市', 成都市);
import 德阳市 from '@/mock/areas/510600.json';
echarts.registerMap('德阳市', 德阳市);
import 达州市 from '@/mock/areas/511700.json';
echarts.registerMap('达州市', 达州市);
import 广元市 from '@/mock/areas/510800.json';
echarts.registerMap('广元市', 广元市);
import 广安市 from '@/mock/areas/511600.json';
echarts.registerMap('广安市', 广安市);
import 甘孜藏族自治州 from '@/mock/areas/513300.json';
echarts.registerMap('甘孜藏族自治州', 甘孜藏族自治州);
import 凉山彝族自治州 from '@/mock/areas/513400.json';
echarts.registerMap('凉山彝族自治州', 凉山彝族自治州);
import 乐山市 from '@/mock/areas/511100.json';
echarts.registerMap('乐山市', 乐山市);
import 绵阳市 from '@/mock/areas/510700.json';
echarts.registerMap('绵阳市', 绵阳市);
import 眉山市 from '@/mock/areas/511400.json';
echarts.registerMap('眉山市', 眉山市);
import 泸州市 from '@/mock/areas/510500.json';
echarts.registerMap('泸州市', 泸州市);
import 南充市 from '@/mock/areas/511300.json';
echarts.registerMap('南充市', 南充市);
import 攀枝花市 from '@/mock/areas/510400.json';
echarts.registerMap('攀枝花市', 攀枝花市);
import 内江市 from '@/mock/areas/511000.json';
echarts.registerMap('内江市', 内江市);
import 遂宁市 from '@/mock/areas/510900.json';
echarts.registerMap('遂宁市', 遂宁市);
import 雅安市 from '@/mock/areas/511800.json';
echarts.registerMap('雅安市', 雅安市);
import 宜宾市 from '@/mock/areas/511500.json';
echarts.registerMap('宜宾市', 宜宾市);
import 资阳市 from '@/mock/areas/512000.json';
echarts.registerMap('资阳市', 资阳市);
import 自贡市 from '@/mock/areas/510300.json';
echarts.registerMap('自贡市', 自贡市);
import 香港特别行政区 from '@/mock/areas/810000.json';
echarts.registerMap('香港特别行政区', 香港特别行政区);
import 西藏自治区 from '@/mock/areas/540000.json';
echarts.registerMap('西藏自治区', 西藏自治区);
import 阿里地区 from '@/mock/areas/542500.json';
echarts.registerMap('阿里地区', 阿里地区);
import 昌都市 from '@/mock/areas/540300.json';
echarts.registerMap('昌都市', 昌都市);
import 拉萨市 from '@/mock/areas/540100.json';
echarts.registerMap('拉萨市', 拉萨市);
import 林芝市 from '@/mock/areas/540400.json';
echarts.registerMap('林芝市', 林芝市);
import 那曲地区 from '@/mock/areas/542400.json';
echarts.registerMap('那曲地区', 那曲地区);
import 山南市 from '@/mock/areas/540500.json';
echarts.registerMap('山南市', 山南市);
import 日喀则市 from '@/mock/areas/540200.json';
echarts.registerMap('日喀则市', 日喀则市);
import 云南省 from '@/mock/areas/530000.json';
echarts.registerMap('云南省', 云南省);
import 保山市 from '@/mock/areas/530500.json';
echarts.registerMap('保山市', 保山市);
import 楚雄彝族自治州 from '@/mock/areas/532300.json';
echarts.registerMap('楚雄彝族自治州', 楚雄彝族自治州);
import 大理白族自治州 from '@/mock/areas/532900.json';
echarts.registerMap('大理白族自治州', 大理白族自治州);
import 德宏傣族景颇族自治州 from '@/mock/areas/533100.json';
echarts.registerMap('德宏傣族景颇族自治州', 德宏傣族景颇族自治州);
import 迪庆藏族自治州 from '@/mock/areas/533400.json';
echarts.registerMap('迪庆藏族自治州', 迪庆藏族自治州);
import 红河哈尼族彝族自治州 from '@/mock/areas/532500.json';
echarts.registerMap('红河哈尼族彝族自治州', 红河哈尼族彝族自治州);
import 昆明市 from '@/mock/areas/530100.json';
echarts.registerMap('昆明市', 昆明市);
import 丽江市 from '@/mock/areas/530700.json';
echarts.registerMap('丽江市', 丽江市);
import 临沧市 from '@/mock/areas/530900.json';
echarts.registerMap('临沧市', 临沧市);
import 怒江傈僳族自治州 from '@/mock/areas/533300.json';
echarts.registerMap('怒江傈僳族自治州', 怒江傈僳族自治州);
import 曲靖市 from '@/mock/areas/530300.json';
echarts.registerMap('曲靖市', 曲靖市);
import 普洱市 from '@/mock/areas/530800.json';
echarts.registerMap('普洱市', 普洱市);
import 文山壮族苗族自治州 from '@/mock/areas/532600.json';
echarts.registerMap('文山壮族苗族自治州', 文山壮族苗族自治州);
import 西双版纳傣族自治州 from '@/mock/areas/532800.json';
echarts.registerMap('西双版纳傣族自治州', 西双版纳傣族自治州);
import 玉溪市 from '@/mock/areas/530400.json';
echarts.registerMap('玉溪市', 玉溪市);
import 昭通市 from '@/mock/areas/530600.json';
echarts.registerMap('昭通市', 昭通市);
import 浙江省 from '@/mock/areas/330000.json';
echarts.registerMap('浙江省', 浙江省);
import 杭州市 from '@/mock/areas/330100.json';
echarts.registerMap('杭州市', 杭州市);
import 嘉兴市 from '@/mock/areas/330400.json';
echarts.registerMap('嘉兴市', 嘉兴市);
import 湖州市 from '@/mock/areas/330500.json';
echarts.registerMap('湖州市', 湖州市);
import 丽水市 from '@/mock/areas/331100.json';
echarts.registerMap('丽水市', 丽水市);
import 金华市 from '@/mock/areas/330700.json';
echarts.registerMap('金华市', 金华市);
import 衢州市 from '@/mock/areas/330800.json';
echarts.registerMap('衢州市', 衢州市);
import 宁波市 from '@/mock/areas/330200.json';
echarts.registerMap('宁波市', 宁波市);
import 绍兴市 from '@/mock/areas/330600.json';
echarts.registerMap('绍兴市', 绍兴市);
import 台州市 from '@/mock/areas/331000.json';
echarts.registerMap('台州市', 台州市);
import 温州市 from '@/mock/areas/330300.json';
echarts.registerMap('温州市', 温州市);
import 舟山市 from '@/mock/areas/330900.json';
echarts.registerMap('舟山市', 舟山市);

if (!localStorage.getItem('info'))
    localStorage.setItem('info', JSON.stringify({ country: '中国', province: '', city: '', isDrill: true, level: 0, type: 'normal' }));
